Repository evopy/evopy, pull requests merged in 2019-05, with the labels that each got.

#1 Test Travis build failures
  .travis.yml
  README.md
  setup.py
  test/__init__.py
Labels: chore

#3 Add Travis badge and installation instructions
  README.md
Labels: chore

#2 Add initial code for the simplest working evolutionary strategy algorithm
  evopy/__init__.py
  evopy/evopy.py
  evopy/individual.py
  test/test_evopy.py
Labels: enhancement

#7 Wrap run function in class
  .pylintrc
  evopy/__init__.py
  evopy/evopy.py
  evopy/individual.py
  test/test_evopy.py
Labels: chore, enhancement

#11 Add progress reporter
  .pylintrc
  evopy/__init__.py
  evopy/evopy.py
  evopy/progress_report.py
  test/test_evopy.py
Labels: enhancement

#15 Adds two usage examples to the README
  README.md
  test/test_evopy.py
Labels: enhancement

#17 Setup docs on readthedocs.io
  .gitignore
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  setup.py
Labels: chore

#19 Release version 0.2
  docs/conf.py
  setup.py
Labels: chore

#25 Release 0.2.2
  docs/conf.py
  setup.py
Labels: release

#26 Add codecov badge
  README.md
Labels: chore
